package Sport;

import Classes.AI;
import Classes.Game;
import Classes.GameRules;
import Interface.IPlayer;
import Interface.ITactic;
import Interface.ITeam;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

public class GameFootball extends Game {

    private float homeOffense, homeDefense, awayOffense, awayDefense;    
    private Map<IPlayer, Integer> playerYellowCards = new HashMap<>();

    public GameFootball(ITeam homeTeam, ITeam awayTeam, GameRules rules, ITactic homeTactic, ITactic awayTactic) {
        super(homeTeam, awayTeam, rules, homeTactic, awayTactic);
    }

    @Override
    protected void preMatchSetup() {
        // Maç tam başlarken menajerlere taktiklerini/kadrolarını sor!
        if (homeManager != null) this.homeTactic = homeManager.generateStartingTactic();
        if (awayManager != null) this.awayTactic = awayManager.generateStartingTactic();

        addLogEntry("--- MAÇ BAŞLADI: " + homeTeam.getName() + " vs " + awayTeam.getName() + " ---");
        addLogEntry("Ev Sahibi Taktik: " + homeTactic.getFormation() + " | Deplasman Taktik: " + awayTactic.getFormation());

        // Lineups are now generated by the AI before the game starts.
        // This check is removed as it would override the AI's choices.

        Sport.PositionsFootball.resolvePositionCollisions(homeTactic);
        Sport.PositionsFootball.resolvePositionCollisions(awayTactic);

        recalculateTeamStrengths();

        homeSubsLeft = rules.getSubstitutionCount();
        awaySubsLeft = rules.getSubstitutionCount();
        
        logFormationGrid(homeTeam, homeTactic, "Maç Başı");
        logFormationGrid(awayTeam, awayTactic, "Maç Başı");
    }

    private void recalculateTeamStrengths() {
        float homeRatio = Math.max(0.1f, homeTactic.getStartingLineup().size() / 11.0f);
        float awayRatio = Math.max(0.1f, awayTactic.getStartingLineup().size() / 11.0f);
        
        homeOffense = homeTeam.getTotalOffensiveRating() * homeTactic.getTotalXGMultiplier() * homeRatio;
        homeDefense = homeTeam.getTotalDefensiveRating() * homeTactic.getTotalXGAMultiplier() * (1.0f / homeRatio);
        awayOffense = awayTeam.getTotalOffensiveRating() * awayTactic.getTotalXGMultiplier() * awayRatio;
        awayDefense = awayTeam.getTotalDefensiveRating() * awayTactic.getTotalXGAMultiplier() * (1.0f / awayRatio);
    }

    private void performSubstitution(ITeam team, ITactic tactic, int minute, String reason) {
        List<IPlayer> onField = tactic.getStartingLineup();
        List<IPlayer> bench = tactic.getSubstitutes();
        
        if (onField.isEmpty() || bench.isEmpty()) return;

        logFormationGrid(team, tactic, minute + "'. Değişiklik Öncesi");

        int outIndex = getRandom().nextInt(onField.size());
        int inIndex = getRandom().nextInt(bench.size());

        IPlayer playerOut = onField.remove(outIndex);
        IPlayer playerIn = bench.remove(inIndex);
        
        if (playerOut instanceof Classes.Player) {
            if (reason.contains("Sakatlık")) {
                double randChance = getRandom().nextDouble();
                int duration = 3;
                if (randChance < 0.05) duration = 1;
                else if (randChance < 0.10) duration = 2;
                ((Classes.Player) playerOut).setInjuryDuration(duration);
            }
        }

        if (playerOut instanceof Classes.Player && playerIn instanceof Classes.Player) {
            ((Classes.Player) playerIn).setCurrentPositionId(((Classes.Player) playerOut).getCurrentPositionId());
        }
        
        onField.add(playerIn);
        bench.add(playerOut);
        
        addLogEntry(minute + "'. " + reason + " (" + team.getName() + ") -> Çıkan: " + playerOut.getFullName() + " | Giren: " + playerIn.getFullName());
        
        Sport.PositionsFootball.resolvePositionCollisions(tactic);
        logFormationGrid(team, tactic, minute + "'. Değişiklik Sonrası");
    }

    @Override
    protected void simulatePeriod(int periodNumber) {
        int duration = rules.getPeriodDuration();
        int startMinute = ((periodNumber - 1) * duration) + 1;
        int endMinute = periodNumber * duration;

        for (int minute = startMinute; minute <= endMinute; minute++) {

            if (getRandom().nextDouble() < 0.03) {
                if (getRandom().nextBoolean()) {
                    if (homeTeam.isManagerAI()) {
                        if (homeSubsLeft > 0) {
                            performSubstitution(homeTeam, homeTactic, minute, "MECBURİ DEĞİŞİKLİK (Sakatlık)");
                            homeSubsLeft--;
                        }
                    } else {
                        handlePlayerInjury(homeTeam, homeTactic, minute);
                    }
                } else {
                    if (awayTeam.isManagerAI()) {
                        if (awaySubsLeft > 0) {
                            performSubstitution(awayTeam, awayTactic, minute, "MECBURİ DEĞİŞİKLİK (Sakatlık)");
                            awaySubsLeft--;
                        }
                    } else {
                        handlePlayerInjury(awayTeam, awayTactic, minute);
                    }
                }
            }

            double yellowCardChance = 0.025; // Her dakika %0.5 sarı kart çıkma ihtimali
            double directRedCardChance = 0.01; // %0.1 ihtimalle doğrudan kırmızı kart

            // Ev sahibi için kart kontrolü
            if (getRandom().nextDouble() < yellowCardChance) {
                handleYellowCard(homeTeam, homeTactic, minute);
            } else if (getRandom().nextDouble() < directRedCardChance) {
                handleRedCard(homeTeam, homeTactic, minute);
            }

            // Deplasman için kart kontrolü
            if (getRandom().nextDouble() < yellowCardChance) {
                handleYellowCard(awayTeam, awayTactic, minute);
            } else if (getRandom().nextDouble() < directRedCardChance) {
                handleRedCard(awayTeam, awayTactic, minute);
            }

            double homeGoalChance = (homeOffense / (homeOffense + awayDefense)) * 0.025;
            if (getRandom().nextDouble() < homeGoalChance) { 
                homeScore++;
                addLogEntry(minute + "'. GOOOAALLL! " + homeTeam.getName() + " ağları sarsıyor! Skor: " + homeScore + "-" + awayScore);
            }

            double awayGoalChance = (awayOffense / (awayOffense + homeDefense)) * 0.025;
            if (getRandom().nextDouble() < awayGoalChance) {
                awayScore++;
                addLogEntry(minute + "'. GOOOAALLL! " + awayTeam.getName() + " golü buldu! Skor: " + homeScore + "-" + awayScore);
            }
        }
    }

    private void handleRedCard(ITeam team, ITactic tactic, int minute) {
        List<IPlayer> onField = tactic.getStartingLineup();
        if (onField.isEmpty()) return;
        int outIndex = getRandom().nextInt(onField.size());
        IPlayer redCarded = onField.remove(outIndex);
        addLogEntry(minute + "'. KIRMIZI KART! (" + team.getName() + ") -> Oyundan Atılan: " + redCarded.getFullName());
        Sport.PositionsFootball.resolvePositionCollisions(tactic);
        recalculateTeamStrengths();
        logFormationGrid(team, tactic, minute + "'. Kırmızı Kart Sonrası");
    }

    private void handleYellowCard(ITeam team, ITactic tactic, int minute) {
     List<IPlayer> onField = tactic.getStartingLineup();
     if (onField.isEmpty()) return;

     int playerIndex = getRandom().nextInt(onField.size());
     IPlayer bookedPlayer = onField.get(playerIndex);

     // Oyuncunun mevcut sarı kart sayısını al ve 1 artır
     int currentYellows = playerYellowCards.getOrDefault(bookedPlayer, 0) + 1;
     playerYellowCards.put(bookedPlayer, currentYellows);

     addLogEntry(minute + "'. SARI KART! (" + team.getName() + ") -> Oyuncu: " + bookedPlayer.getFullName());

     // Eğer 2 sarı karta (GameRulesFootball'dan gelir) ulaştıysa oyundan at
     if (currentYellows >= rules.getYellowCardsForRed()) {
         addLogEntry(minute + "'. İKİNCİ SARI KARTTAN KIRMIZI KART! (" + team.getName() + ") -> Oyundan Atılan: " + bookedPlayer.getFullName());
         onField.remove(playerIndex);
         Sport.PositionsFootball.resolvePositionCollisions(tactic);
         recalculateTeamStrengths();
         logFormationGrid(team, tactic, minute + "'. Kırmızı Kart Sonrası");
     }
 }

    private void handlePlayerInjury(ITeam team, ITactic tactic, int minute) {
        List<IPlayer> onField = tactic.getStartingLineup();
        if (onField.isEmpty()) return;
        
        int outIndex = getRandom().nextInt(onField.size());
        IPlayer injured = onField.remove(outIndex);
        
        if (injured instanceof Classes.Player) {
            double randChance = getRandom().nextDouble();
            int duration = 3;
            if (randChance < 0.05) duration = 1;
            else if (randChance < 0.10) duration = 2;
            ((Classes.Player) injured).setInjuryDuration(duration);
        }
        
        
        addLogEntry(minute + "'. SAKATLIK! (" + team.getName() + ") -> Sakatlanan: " + injured.getFullName() + ". Oyuncu tedavi için kenara alındı.");
        Sport.PositionsFootball.resolvePositionCollisions(tactic);
        recalculateTeamStrengths();
        logFormationGrid(team, tactic, minute + "'. Sakatlık Sonrası");
    }

    @Override
    protected void handlePeriodBreak(int periodNumber) {
        addLogEntry("--- HAKEM " + periodNumber + ". PERİYODU BİTİREN DÜDÜĞÜ ÇALDI. SKOR: " + homeScore + " - " + awayScore + " ---");

        if (homeManager != null) {
            logFormationGrid(homeTeam, homeTactic, "Devre Arası Değişiklik Öncesi");
            if (homeTeam.isManagerAI()) addLogEntry("Ev sahibi (" + homeTeam.getName() + ") devre arası taktik değişikliği yapıyor...");
            homeManager.handlePeriodBreak(this, homeTactic, periodNumber);
            Sport.PositionsFootball.resolvePositionCollisions(homeTactic);
            logFormationGrid(homeTeam, homeTactic, "Devre Arası Değişiklik Sonrası");
        }

        if (awayManager != null) {
            logFormationGrid(awayTeam, awayTactic, "Devre Arası Değişiklik Öncesi");
            if (awayTeam.isManagerAI()) addLogEntry("Deplasman takımı (" + awayTeam.getName() + ") devre arası taktik değişikliği yapıyor...");
            awayManager.handlePeriodBreak(this, awayTactic, periodNumber);
            Sport.PositionsFootball.resolvePositionCollisions(awayTactic);
            logFormationGrid(awayTeam, awayTactic, "Devre Arası Değişiklik Sonrası");
        }

        recalculateTeamStrengths();
    }

    private void logFormationGrid(ITeam team, ITactic tactic, String context) {
        String[][] grid = new String[10][10];
        for (int y = 0; y < 10; y++) {
            for (int x = 0; x < 10; x++) {
                grid[y][x] = "";
            }
        }

        for (IPlayer p : tactic.getStartingLineup()) {
            int posId = p.getPrimaryPositionId();
            String label = "?";
            if (p instanceof Classes.Player) {
                posId = ((Classes.Player) p).getCurrentPositionId();
                label = String.valueOf(((Classes.Player) p).getJerseyNumber());
            }
            int x = posId % 10;
            int y = posId / 10;
            if (x >= 0 && x < 10 && y >= 0 && y < 10) {
                if (grid[y][x].isEmpty()) {
                    grid[y][x] = label;
                } else {
                    grid[y][x] += "," + label;
                }
            }
        }

        addLogEntry("");
        addLogEntry(context + " - " + team.getName() + " 10x10 Saha Dizilişi:");
        addLogEntry("+----------------------------------------+");
        for (int y = 9; y >= 0; y--) {
            StringBuilder row = new StringBuilder("|");
            for (int x = 0; x < 10; x++) {
                if (!grid[y][x].isEmpty()) {
                    row.append(String.format("%-4s", grid[y][x])); 
                } else {
                    row.append(".   "); 
                }
            }
            row.append("|");
            addLogEntry(row.toString());
        }
        addLogEntry("+----------------------------------------+");
        addLogEntry("");
    }

    public double getHomeXG() {
        double hOff = homeTeam.getTotalOffensiveRating();
        double aDef = awayTeam.getTotalDefensiveRating();
        double hXG = (hOff / (hOff + aDef)) * 2.25;
        return Double.isNaN(hXG) || Double.isInfinite(hXG) ? 1.0 : hXG;
    }

    public double getAwayXG() {
        double aOff = awayTeam.getTotalOffensiveRating();
        double hDef = homeTeam.getTotalDefensiveRating();
        double aXG = (aOff / (aOff + hDef)) * 2.25;
        return Double.isNaN(aXG) || Double.isInfinite(aXG) ? 1.0 : aXG;
    }

    public int getHomePossession() {
        double hOff = homeTeam.getTotalOffensiveRating();
        double aOff = awayTeam.getTotalOffensiveRating();
        int possH = (int) Math.round((hOff / (hOff + aOff)) * 100);
        if (possH < 10) return 50;
        if (possH > 90) return 90;
        return possH;
    }

    public double getHomeShotChance(int homePossession) {
        return (homePossession / 100.0) * 0.15;
    }

    public double getAwayShotChance(int homePossession) {
        return ((100 - homePossession) / 100.0) * 0.15;
    }

    public String getEventType(String log) {
        if (log.contains("GOOOAALLL")) return "GOAL";
        if (log.contains("SARI KART!") && !log.contains("KIRMIZI KART!")) return "YELLOW";
        if (log.contains("KIRMIZI KART!")) return "RED";
        if (log.contains("Sakatlık") || log.contains("MECBURİ") || log.contains("SAKATLIK!")) return "INJURY";
        if (log.contains("Değişiklik")) return "SUB";
        return "INFO";
    }

    @Override
    protected void postMatchCleanup() {
        addLogEntry("--- MAÇ SONA ERDİ! SKOR: " + homeScore + " - " + awayScore + " ---");
        
        logFormationGrid(homeTeam, homeTactic, "Maç Sonu");
        logFormationGrid(awayTeam, awayTactic, "Maç Sonu");
        
        homeTeam.setGoalsScored(homeTeam.getGoalsScored() + homeScore);
        homeTeam.setGoalsConceded(homeTeam.getGoalsConceded() + awayScore);
        awayTeam.setGoalsScored(awayTeam.getGoalsScored() + awayScore);
        awayTeam.setGoalsConceded(awayTeam.getGoalsConceded() + homeScore);

        if (homeScore > awayScore) {
            homeTeam.setWins(homeTeam.getWins() + 1);
            homeTeam.setPoints(homeTeam.getPoints() + rules.getVictoryPoints());
            awayTeam.setLosses(awayTeam.getLosses() + 1);
            awayTeam.setPoints(awayTeam.getPoints() + rules.getDefeatPoints());
        } else if (awayScore > homeScore) {
            awayTeam.setWins(awayTeam.getWins() + 1);
            awayTeam.setPoints(awayTeam.getPoints() + rules.getVictoryPoints());
            homeTeam.setLosses(homeTeam.getLosses() + 1);
            homeTeam.setPoints(homeTeam.getPoints() + rules.getDefeatPoints());
        } else {
            homeTeam.setDraws(homeTeam.getDraws() + 1);
            homeTeam.setPoints(homeTeam.getPoints() + rules.getDrawPoints());
            awayTeam.setDraws(awayTeam.getDraws() + 1);
            awayTeam.setPoints(awayTeam.getPoints() + rules.getDrawPoints());
        }
    }
}