package Sport;

import Classes.AI;
import Classes.Game;
import Classes.GameRules;
import Interface.IPlayer;
import Interface.ITactic;
import Interface.ITeam;

import java.util.ArrayList;
import java.util.List;

public class GameFootball extends Game {

    private float homeOffense, homeDefense, awayOffense, awayDefense;    

    public GameFootball(ITeam homeTeam, ITeam awayTeam, GameRules rules, ITactic homeTactic, ITactic awayTactic) {
        super(homeTeam, awayTeam, rules, homeTactic, awayTactic);
    }

    @Override
    protected void preMatchSetup() {
        // Maç tam başlarken menajerlere taktiklerini/kadrolarını sor!
        if (homeManager != null) this.homeTactic = homeManager.generateStartingTactic();
        if (awayManager != null) this.awayTactic = awayManager.generateStartingTactic();

        addLogEntry("--- MAÇ BAŞLADI: " + homeTeam.getName() + " vs " + awayTeam.getName() + " ---");
        addLogEntry("Ev Sahibi Taktik: " + homeTactic.getFormation() + " | Deplasman Taktik: " + awayTactic.getFormation());

        // Lineups are now generated by the AI before the game starts.
        // This check is removed as it would override the AI's choices.

        Sport.PositionsFootball.resolvePositionCollisions(homeTactic);
        Sport.PositionsFootball.resolvePositionCollisions(awayTactic);

        recalculateTeamStrengths();

        homeSubsLeft = rules.getSubstitutionCount();
        awaySubsLeft = rules.getSubstitutionCount();
        
        logFormationGrid(homeTeam, homeTactic, "Maç Başı");
        logFormationGrid(awayTeam, awayTactic, "Maç Başı");
    }

    private void recalculateTeamStrengths() {
        float homeRatio = Math.max(0.1f, homeTactic.getStartingLineup().size() / 11.0f);
        float awayRatio = Math.max(0.1f, awayTactic.getStartingLineup().size() / 11.0f);
        
        homeOffense = homeTeam.getTotalOffensiveRating() * homeTactic.getTotalXGMultiplier() * homeRatio;
        homeDefense = homeTeam.getTotalDefensiveRating() * homeTactic.getTotalXGAMultiplier() * (1.0f / homeRatio);
        awayOffense = awayTeam.getTotalOffensiveRating() * awayTactic.getTotalXGMultiplier() * awayRatio;
        awayDefense = awayTeam.getTotalDefensiveRating() * awayTactic.getTotalXGAMultiplier() * (1.0f / awayRatio);
    }

    private void performSubstitution(ITeam team, ITactic tactic, int minute, String reason) {
        List<IPlayer> onField = tactic.getStartingLineup();
        List<IPlayer> bench = tactic.getSubstitutes();
        
        if (onField.isEmpty() || bench.isEmpty()) return;

        logFormationGrid(team, tactic, minute + "'. Değişiklik Öncesi");

        int outIndex = getRandom().nextInt(onField.size());
        int inIndex = getRandom().nextInt(bench.size());

        IPlayer playerOut = onField.remove(outIndex);
        IPlayer playerIn = bench.remove(inIndex);
        
        if (playerOut instanceof Classes.Player && playerIn instanceof Classes.Player) {
            ((Classes.Player) playerIn).setCurrentPositionId(((Classes.Player) playerOut).getCurrentPositionId());
        }
        
        onField.add(playerIn);
        
        addLogEntry(minute + "'. " + reason + " (" + team.getName() + ") -> Çıkan: " + playerOut.getFullName() + " | Giren: " + playerIn.getFullName());
        
        Sport.PositionsFootball.resolvePositionCollisions(tactic);
        logFormationGrid(team, tactic, minute + "'. Değişiklik Sonrası");
    }

    @Override
    protected void simulatePeriod(int periodNumber) {
        int duration = rules.getPeriodDuration();
        int startMinute = ((periodNumber - 1) * duration) + 1;
        int endMinute = periodNumber * duration;

        for (int minute = startMinute; minute <= endMinute; minute++) {

            if (getRandom().nextDouble() < 0.01) {
                if (getRandom().nextBoolean() && homeSubsLeft > 0) {
                    performSubstitution(homeTeam, homeTactic, minute, "MECBURİ DEĞİŞİKLİK (Sakatlık)");
                    homeSubsLeft--;
                } else if (awaySubsLeft > 0) {
                    performSubstitution(awayTeam, awayTactic, minute, "MECBURİ DEĞİŞİKLİK (Sakatlık)");
                    awaySubsLeft--;
                }
            }

            if (getRandom().nextDouble() < 0.001) {
                handleRedCard(homeTeam, homeTactic, minute);
            }
            if (getRandom().nextDouble() < 0.001) {
                handleRedCard(awayTeam, awayTactic, minute);
            }

            double homeGoalChance = (homeOffense / (homeOffense + awayDefense)) * 0.025;
            if (getRandom().nextDouble() < homeGoalChance) { 
                homeScore++;
                addLogEntry(minute + "'. GOOOAALLL! " + homeTeam.getName() + " ağları sarsıyor! Skor: " + homeScore + "-" + awayScore);
            }

            double awayGoalChance = (awayOffense / (awayOffense + homeDefense)) * 0.025;
            if (getRandom().nextDouble() < awayGoalChance) {
                awayScore++;
                addLogEntry(minute + "'. GOOOAALLL! " + awayTeam.getName() + " golü buldu! Skor: " + homeScore + "-" + awayScore);
            }
        }
    }

    private void handleRedCard(ITeam team, ITactic tactic, int minute) {
        List<IPlayer> onField = tactic.getStartingLineup();
        if (onField.isEmpty()) return;
        int outIndex = getRandom().nextInt(onField.size());
        IPlayer redCarded = onField.remove(outIndex);
        addLogEntry(minute + "'. KIRMIZI KART! (" + team.getName() + ") -> Oyundan Atılan: " + redCarded.getFullName());
        Sport.PositionsFootball.resolvePositionCollisions(tactic);
        recalculateTeamStrengths();
        logFormationGrid(team, tactic, minute + "'. Kırmızı Kart Sonrası");
    }

    @Override
    protected void handlePeriodBreak(int periodNumber) {
        addLogEntry("--- HAKEM " + periodNumber + ". PERİYODU BİTİREN DÜDÜĞÜ ÇALDI. SKOR: " + homeScore + " - " + awayScore + " ---");

        if (homeManager != null) {
            logFormationGrid(homeTeam, homeTactic, "Devre Arası Değişiklik Öncesi");
            if (homeTeam.isManagerAI()) addLogEntry("Ev sahibi (" + homeTeam.getName() + ") devre arası taktik değişikliği yapıyor...");
            homeManager.handlePeriodBreak(this, homeTactic, periodNumber);
            Sport.PositionsFootball.resolvePositionCollisions(homeTactic);
            logFormationGrid(homeTeam, homeTactic, "Devre Arası Değişiklik Sonrası");
        }

        if (awayManager != null) {
            logFormationGrid(awayTeam, awayTactic, "Devre Arası Değişiklik Öncesi");
            if (awayTeam.isManagerAI()) addLogEntry("Deplasman takımı (" + awayTeam.getName() + ") devre arası taktik değişikliği yapıyor...");
            awayManager.handlePeriodBreak(this, awayTactic, periodNumber);
            Sport.PositionsFootball.resolvePositionCollisions(awayTactic);
            logFormationGrid(awayTeam, awayTactic, "Devre Arası Değişiklik Sonrası");
        }

        recalculateTeamStrengths();
    }

    private void logFormationGrid(ITeam team, ITactic tactic, String context) {
        String[][] grid = new String[10][10];
        for (int y = 0; y < 10; y++) {
            for (int x = 0; x < 10; x++) {
                grid[y][x] = "";
            }
        }

        for (IPlayer p : tactic.getStartingLineup()) {
            int posId = p.getPrimaryPositionId();
            String label = "?";
            if (p instanceof Classes.Player) {
                posId = ((Classes.Player) p).getCurrentPositionId();
                label = String.valueOf(((Classes.Player) p).getJerseyNumber());
            }
            int x = posId % 10;
            int y = posId / 10;
            if (x >= 0 && x < 10 && y >= 0 && y < 10) {
                if (grid[y][x].isEmpty()) {
                    grid[y][x] = label;
                } else {
                    grid[y][x] += "," + label;
                }
            }
        }

        addLogEntry("");
        addLogEntry(context + " - " + team.getName() + " 10x10 Saha Dizilişi:");
        addLogEntry("+----------------------------------------+");
        for (int y = 9; y >= 0; y--) {
            StringBuilder row = new StringBuilder("|");
            for (int x = 0; x < 10; x++) {
                if (!grid[y][x].isEmpty()) {
                    row.append(String.format("%-4s", grid[y][x])); 
                } else {
                    row.append(".   "); 
                }
            }
            row.append("|");
            addLogEntry(row.toString());
        }
        addLogEntry("+----------------------------------------+");
        addLogEntry("");
    }

    @Override
    protected void postMatchCleanup() {
        addLogEntry("--- MAÇ SONA ERDİ! SKOR: " + homeScore + " - " + awayScore + " ---");
        
        logFormationGrid(homeTeam, homeTactic, "Maç Sonu");
        logFormationGrid(awayTeam, awayTactic, "Maç Sonu");
        
        homeTeam.setGoalsScored(homeTeam.getGoalsScored() + homeScore);
        homeTeam.setGoalsConceded(homeTeam.getGoalsConceded() + awayScore);
        awayTeam.setGoalsScored(awayTeam.getGoalsScored() + awayScore);
        awayTeam.setGoalsConceded(awayTeam.getGoalsConceded() + homeScore);

        if (homeScore > awayScore) {
            homeTeam.setWins(homeTeam.getWins() + 1);
            homeTeam.setPoints(homeTeam.getPoints() + rules.getVictoryPoints());
            awayTeam.setLosses(awayTeam.getLosses() + 1);
            awayTeam.setPoints(awayTeam.getPoints() + rules.getDefeatPoints());
        } else if (awayScore > homeScore) {
            awayTeam.setWins(awayTeam.getWins() + 1);
            awayTeam.setPoints(awayTeam.getPoints() + rules.getVictoryPoints());
            homeTeam.setLosses(homeTeam.getLosses() + 1);
            homeTeam.setPoints(homeTeam.getPoints() + rules.getDefeatPoints());
        } else {
            homeTeam.setDraws(homeTeam.getDraws() + 1);
            homeTeam.setPoints(homeTeam.getPoints() + rules.getDrawPoints());
            awayTeam.setDraws(awayTeam.getDraws() + 1);
            awayTeam.setPoints(awayTeam.getPoints() + rules.getDrawPoints());
        }
    }
}